/// <auto-generated />
using System;
using Kokuban.AnsiEscape;

namespace Kokuban
{
    public partial class Chalk
    {
        public static AnsiStyleBuilder Black => new AnsiStyleBuilder().Black;
        public static AnsiStyleBuilder Red => new AnsiStyleBuilder().Red;
        public static AnsiStyleBuilder Green => new AnsiStyleBuilder().Green;
        public static AnsiStyleBuilder Yellow => new AnsiStyleBuilder().Yellow;
        public static AnsiStyleBuilder Blue => new AnsiStyleBuilder().Blue;
        public static AnsiStyleBuilder Magenta => new AnsiStyleBuilder().Magenta;
        public static AnsiStyleBuilder Cyan => new AnsiStyleBuilder().Cyan;
        public static AnsiStyleBuilder White => new AnsiStyleBuilder().White;
        public static AnsiStyleBuilder Gray => new AnsiStyleBuilder().Gray;
        public static AnsiStyleBuilder Grey => new AnsiStyleBuilder().Grey;
        public static AnsiStyleBuilder BrightBlack => new AnsiStyleBuilder().BrightBlack;
        public static AnsiStyleBuilder BrightRed => new AnsiStyleBuilder().BrightRed;
        public static AnsiStyleBuilder BrightGreen => new AnsiStyleBuilder().BrightGreen;
        public static AnsiStyleBuilder BrightYellow => new AnsiStyleBuilder().BrightYellow;
        public static AnsiStyleBuilder BrightBlue => new AnsiStyleBuilder().BrightBlue;
        public static AnsiStyleBuilder BrightMagenta => new AnsiStyleBuilder().BrightMagenta;
        public static AnsiStyleBuilder BrightCyan => new AnsiStyleBuilder().BrightCyan;
        public static AnsiStyleBuilder BrightWhite => new AnsiStyleBuilder().BrightWhite;
        public static AnsiStyleBuilder BgBlack => new AnsiStyleBuilder().BgBlack;
        public static AnsiStyleBuilder BgRed => new AnsiStyleBuilder().BgRed;
        public static AnsiStyleBuilder BgGreen => new AnsiStyleBuilder().BgGreen;
        public static AnsiStyleBuilder BgYellow => new AnsiStyleBuilder().BgYellow;
        public static AnsiStyleBuilder BgBlue => new AnsiStyleBuilder().BgBlue;
        public static AnsiStyleBuilder BgMagenta => new AnsiStyleBuilder().BgMagenta;
        public static AnsiStyleBuilder BgCyan => new AnsiStyleBuilder().BgCyan;
        public static AnsiStyleBuilder BgWhite => new AnsiStyleBuilder().BgWhite;
        public static AnsiStyleBuilder BgGray => new AnsiStyleBuilder().BgGray;
        public static AnsiStyleBuilder BgGrey => new AnsiStyleBuilder().BgGrey;
        public static AnsiStyleBuilder BgBrightBlack => new AnsiStyleBuilder().BgBrightBlack;
        public static AnsiStyleBuilder BgBrightRed => new AnsiStyleBuilder().BgBrightRed;
        public static AnsiStyleBuilder BgBrightGreen => new AnsiStyleBuilder().BgBrightGreen;
        public static AnsiStyleBuilder BgBrightYellow => new AnsiStyleBuilder().BgBrightYellow;
        public static AnsiStyleBuilder BgBrightBlue => new AnsiStyleBuilder().BgBrightBlue;
        public static AnsiStyleBuilder BgBrightMagenta => new AnsiStyleBuilder().BgBrightMagenta;
        public static AnsiStyleBuilder BgBrightCyan => new AnsiStyleBuilder().BgBrightCyan;
        public static AnsiStyleBuilder BgBrightWhite => new AnsiStyleBuilder().BgBrightWhite;
        public static AnsiStyleBuilder Bold => new AnsiStyleBuilder().Bold;
        public static AnsiStyleBuilder Faint => new AnsiStyleBuilder().Faint;
        public static AnsiStyleBuilder Dim => new AnsiStyleBuilder().Dim;
        public static AnsiStyleBuilder Italic => new AnsiStyleBuilder().Italic;
        public static AnsiStyleBuilder Underline => new AnsiStyleBuilder().Underline;
        public static AnsiStyleBuilder Inverse => new AnsiStyleBuilder().Inverse;
        public static AnsiStyleBuilder Overline => new AnsiStyleBuilder().Overline;
    }
    
    public enum KokubanColor
    {
        Black = 30,
        Red = 31,
        Green = 32,
        Yellow = 33,
        Blue = 34,
        Magenta = 35,
        Cyan = 36,
        White = 37,
        Gray = 90,
        Grey = 90,
        BrightBlack = 90,
        BrightRed = 91,
        BrightGreen = 92,
        BrightYellow = 93,
        BrightBlue = 94,
        BrightMagenta = 95,
        BrightCyan = 96,
        BrightWhite = 97,
    }
}

namespace Kokuban.AnsiEscape
{
    public static partial class StringAnsiEscape
    {
        public static string Black(string s) => ForegroundColor(s, KokubanColor.Black);
        public static string Red(string s) => ForegroundColor(s, KokubanColor.Red);
        public static string Green(string s) => ForegroundColor(s, KokubanColor.Green);
        public static string Yellow(string s) => ForegroundColor(s, KokubanColor.Yellow);
        public static string Blue(string s) => ForegroundColor(s, KokubanColor.Blue);
        public static string Magenta(string s) => ForegroundColor(s, KokubanColor.Magenta);
        public static string Cyan(string s) => ForegroundColor(s, KokubanColor.Cyan);
        public static string White(string s) => ForegroundColor(s, KokubanColor.White);
        public static string Gray(string s) => ForegroundColor(s, KokubanColor.Gray);
        public static string Grey(string s) => ForegroundColor(s, KokubanColor.Grey);
        public static string BrightBlack(string s) => ForegroundColor(s, KokubanColor.BrightBlack);
        public static string BrightRed(string s) => ForegroundColor(s, KokubanColor.BrightRed);
        public static string BrightGreen(string s) => ForegroundColor(s, KokubanColor.BrightGreen);
        public static string BrightYellow(string s) => ForegroundColor(s, KokubanColor.BrightYellow);
        public static string BrightBlue(string s) => ForegroundColor(s, KokubanColor.BrightBlue);
        public static string BrightMagenta(string s) => ForegroundColor(s, KokubanColor.BrightMagenta);
        public static string BrightCyan(string s) => ForegroundColor(s, KokubanColor.BrightCyan);
        public static string BrightWhite(string s) => ForegroundColor(s, KokubanColor.BrightWhite);
        public static string BgBlack(string s) => BackgroundColor(s, KokubanColor.Black);
        public static string BgRed(string s) => BackgroundColor(s, KokubanColor.Red);
        public static string BgGreen(string s) => BackgroundColor(s, KokubanColor.Green);
        public static string BgYellow(string s) => BackgroundColor(s, KokubanColor.Yellow);
        public static string BgBlue(string s) => BackgroundColor(s, KokubanColor.Blue);
        public static string BgMagenta(string s) => BackgroundColor(s, KokubanColor.Magenta);
        public static string BgCyan(string s) => BackgroundColor(s, KokubanColor.Cyan);
        public static string BgWhite(string s) => BackgroundColor(s, KokubanColor.White);
        public static string BgGray(string s) => BackgroundColor(s, KokubanColor.Gray);
        public static string BgGrey(string s) => BackgroundColor(s, KokubanColor.Grey);
        public static string BgBrightBlack(string s) => BackgroundColor(s, KokubanColor.BrightBlack);
        public static string BgBrightRed(string s) => BackgroundColor(s, KokubanColor.BrightRed);
        public static string BgBrightGreen(string s) => BackgroundColor(s, KokubanColor.BrightGreen);
        public static string BgBrightYellow(string s) => BackgroundColor(s, KokubanColor.BrightYellow);
        public static string BgBrightBlue(string s) => BackgroundColor(s, KokubanColor.BrightBlue);
        public static string BgBrightMagenta(string s) => BackgroundColor(s, KokubanColor.BrightMagenta);
        public static string BgBrightCyan(string s) => BackgroundColor(s, KokubanColor.BrightCyan);
        public static string BgBrightWhite(string s) => BackgroundColor(s, KokubanColor.BrightWhite);
        public static string Bold(string s) => Decorate(s, 1, 22);
        public static string Faint(string s) => Decorate(s, 2, 22);
        public static string Dim(string s) => Decorate(s, 2, 22);
        public static string Italic(string s) => Decorate(s, 3, 23);
        public static string Underline(string s) => Decorate(s, 4, 24);
        public static string Inverse(string s) => Decorate(s, 7, 27);
        public static string Overline(string s) => Decorate(s, 53, 55);
    }

    public partial struct AnsiStyleBuilder
    {
        public AnsiStyleBuilder Black => Foreground(KokubanColor.Black);
        public AnsiStyleBuilder Red => Foreground(KokubanColor.Red);
        public AnsiStyleBuilder Green => Foreground(KokubanColor.Green);
        public AnsiStyleBuilder Yellow => Foreground(KokubanColor.Yellow);
        public AnsiStyleBuilder Blue => Foreground(KokubanColor.Blue);
        public AnsiStyleBuilder Magenta => Foreground(KokubanColor.Magenta);
        public AnsiStyleBuilder Cyan => Foreground(KokubanColor.Cyan);
        public AnsiStyleBuilder White => Foreground(KokubanColor.White);
        public AnsiStyleBuilder Gray => Foreground(KokubanColor.Gray);
        public AnsiStyleBuilder Grey => Foreground(KokubanColor.Grey);
        public AnsiStyleBuilder BrightBlack => Foreground(KokubanColor.BrightBlack);
        public AnsiStyleBuilder BrightRed => Foreground(KokubanColor.BrightRed);
        public AnsiStyleBuilder BrightGreen => Foreground(KokubanColor.BrightGreen);
        public AnsiStyleBuilder BrightYellow => Foreground(KokubanColor.BrightYellow);
        public AnsiStyleBuilder BrightBlue => Foreground(KokubanColor.BrightBlue);
        public AnsiStyleBuilder BrightMagenta => Foreground(KokubanColor.BrightMagenta);
        public AnsiStyleBuilder BrightCyan => Foreground(KokubanColor.BrightCyan);
        public AnsiStyleBuilder BrightWhite => Foreground(KokubanColor.BrightWhite);
        public AnsiStyleBuilder BgBlack => Background(KokubanColor.Black);
        public AnsiStyleBuilder BgRed => Background(KokubanColor.Red);
        public AnsiStyleBuilder BgGreen => Background(KokubanColor.Green);
        public AnsiStyleBuilder BgYellow => Background(KokubanColor.Yellow);
        public AnsiStyleBuilder BgBlue => Background(KokubanColor.Blue);
        public AnsiStyleBuilder BgMagenta => Background(KokubanColor.Magenta);
        public AnsiStyleBuilder BgCyan => Background(KokubanColor.Cyan);
        public AnsiStyleBuilder BgWhite => Background(KokubanColor.White);
        public AnsiStyleBuilder BgGray => Background(KokubanColor.Gray);
        public AnsiStyleBuilder BgGrey => Background(KokubanColor.Grey);
        public AnsiStyleBuilder BgBrightBlack => Background(KokubanColor.BrightBlack);
        public AnsiStyleBuilder BgBrightRed => Background(KokubanColor.BrightRed);
        public AnsiStyleBuilder BgBrightGreen => Background(KokubanColor.BrightGreen);
        public AnsiStyleBuilder BgBrightYellow => Background(KokubanColor.BrightYellow);
        public AnsiStyleBuilder BgBrightBlue => Background(KokubanColor.BrightBlue);
        public AnsiStyleBuilder BgBrightMagenta => Background(KokubanColor.BrightMagenta);
        public AnsiStyleBuilder BgBrightCyan => Background(KokubanColor.BrightCyan);
        public AnsiStyleBuilder BgBrightWhite => Background(KokubanColor.BrightWhite);
    }

}