/// <auto-generated />
using System;
using Kokuban.AnsiEscape;

namespace Kokuban
{
    public partial class Chalk
    {
        public static AnsiStyleBuilder Black => new AnsiStyleBuilder().Black;
        public static AnsiStyleBuilder Red => new AnsiStyleBuilder().Red;
        public static AnsiStyleBuilder Green => new AnsiStyleBuilder().Green;
        public static AnsiStyleBuilder Yellow => new AnsiStyleBuilder().Yellow;
        public static AnsiStyleBuilder Blue => new AnsiStyleBuilder().Blue;
        public static AnsiStyleBuilder Magenta => new AnsiStyleBuilder().Magenta;
        public static AnsiStyleBuilder Cyan => new AnsiStyleBuilder().Cyan;
        public static AnsiStyleBuilder White => new AnsiStyleBuilder().White;
        public static AnsiStyleBuilder Gray => new AnsiStyleBuilder().Gray;
        public static AnsiStyleBuilder Grey => new AnsiStyleBuilder().Grey;
        public static AnsiStyleBuilder BrightBlack => new AnsiStyleBuilder().BrightBlack;
        public static AnsiStyleBuilder BrightRed => new AnsiStyleBuilder().BrightRed;
        public static AnsiStyleBuilder BrightGreen => new AnsiStyleBuilder().BrightGreen;
        public static AnsiStyleBuilder BrightYellow => new AnsiStyleBuilder().BrightYellow;
        public static AnsiStyleBuilder BrightBlue => new AnsiStyleBuilder().BrightBlue;
        public static AnsiStyleBuilder BrightMagenta => new AnsiStyleBuilder().BrightMagenta;
        public static AnsiStyleBuilder BrightCyan => new AnsiStyleBuilder().BrightCyan;
        public static AnsiStyleBuilder BrightWhite => new AnsiStyleBuilder().BrightWhite;
        public static AnsiStyleBuilder BgBlack => new AnsiStyleBuilder().BgBlack;
        public static AnsiStyleBuilder BgRed => new AnsiStyleBuilder().BgRed;
        public static AnsiStyleBuilder BgGreen => new AnsiStyleBuilder().BgGreen;
        public static AnsiStyleBuilder BgYellow => new AnsiStyleBuilder().BgYellow;
        public static AnsiStyleBuilder BgBlue => new AnsiStyleBuilder().BgBlue;
        public static AnsiStyleBuilder BgMagenta => new AnsiStyleBuilder().BgMagenta;
        public static AnsiStyleBuilder BgCyan => new AnsiStyleBuilder().BgCyan;
        public static AnsiStyleBuilder BgWhite => new AnsiStyleBuilder().BgWhite;
        public static AnsiStyleBuilder BgGray => new AnsiStyleBuilder().BgGray;
        public static AnsiStyleBuilder BgGrey => new AnsiStyleBuilder().BgGrey;
        public static AnsiStyleBuilder BgBrightBlack => new AnsiStyleBuilder().BgBrightBlack;
        public static AnsiStyleBuilder BgBrightRed => new AnsiStyleBuilder().BgBrightRed;
        public static AnsiStyleBuilder BgBrightGreen => new AnsiStyleBuilder().BgBrightGreen;
        public static AnsiStyleBuilder BgBrightYellow => new AnsiStyleBuilder().BgBrightYellow;
        public static AnsiStyleBuilder BgBrightBlue => new AnsiStyleBuilder().BgBrightBlue;
        public static AnsiStyleBuilder BgBrightMagenta => new AnsiStyleBuilder().BgBrightMagenta;
        public static AnsiStyleBuilder BgBrightCyan => new AnsiStyleBuilder().BgBrightCyan;
        public static AnsiStyleBuilder BgBrightWhite => new AnsiStyleBuilder().BgBrightWhite;
        public static AnsiStyleBuilder Bold => new AnsiStyleBuilder().Bold;
        public static AnsiStyleBuilder Faint => new AnsiStyleBuilder().Faint;
        public static AnsiStyleBuilder Dim => new AnsiStyleBuilder().Dim;
        public static AnsiStyleBuilder Italic => new AnsiStyleBuilder().Italic;
        public static AnsiStyleBuilder Underline => new AnsiStyleBuilder().Underline;
        public static AnsiStyleBuilder Inverse => new AnsiStyleBuilder().Inverse;
        public static AnsiStyleBuilder Overline => new AnsiStyleBuilder().Overline;
    }
    
    public enum KokubanColor
    {
        Black = 30,
        Red = 31,
        Green = 32,
        Yellow = 33,
        Blue = 34,
        Magenta = 35,
        Cyan = 36,
        White = 37,
        Gray = 90,
        Grey = 90,
        BrightBlack = 90,
        BrightRed = 91,
        BrightGreen = 92,
        BrightYellow = 93,
        BrightBlue = 94,
        BrightMagenta = 95,
        BrightCyan = 96,
        BrightWhite = 97,
    }
}

namespace Kokuban.AnsiEscape
{
    public static partial class AnsiEscapeCode
    {
        public static (int Begin, int End) Black { get; } = (30, 39);
        public static (int Begin, int End) Red { get; } = (31, 39);
        public static (int Begin, int End) Green { get; } = (32, 39);
        public static (int Begin, int End) Yellow { get; } = (33, 39);
        public static (int Begin, int End) Blue { get; } = (34, 39);
        public static (int Begin, int End) Magenta { get; } = (35, 39);
        public static (int Begin, int End) Cyan { get; } = (36, 39);
        public static (int Begin, int End) White { get; } = (37, 39);
        public static (int Begin, int End) Gray { get; } = (90, 39);
        public static (int Begin, int End) Grey { get; } = (90, 39);
        public static (int Begin, int End) BrightBlack { get; } = (90, 39);
        public static (int Begin, int End) BrightRed { get; } = (91, 39);
        public static (int Begin, int End) BrightGreen { get; } = (92, 39);
        public static (int Begin, int End) BrightYellow { get; } = (93, 39);
        public static (int Begin, int End) BrightBlue { get; } = (94, 39);
        public static (int Begin, int End) BrightMagenta { get; } = (95, 39);
        public static (int Begin, int End) BrightCyan { get; } = (96, 39);
        public static (int Begin, int End) BrightWhite { get; } = (97, 39);
        public static (int Begin, int End) BgBlack { get; } = (40, 49);
        public static (int Begin, int End) BgRed { get; } = (41, 49);
        public static (int Begin, int End) BgGreen { get; } = (42, 49);
        public static (int Begin, int End) BgYellow { get; } = (43, 49);
        public static (int Begin, int End) BgBlue { get; } = (44, 49);
        public static (int Begin, int End) BgMagenta { get; } = (45, 49);
        public static (int Begin, int End) BgCyan { get; } = (46, 49);
        public static (int Begin, int End) BgWhite { get; } = (47, 49);
        public static (int Begin, int End) BgGray { get; } = (100, 49);
        public static (int Begin, int End) BgGrey { get; } = (100, 49);
        public static (int Begin, int End) BgBrightBlack { get; } = (100, 49);
        public static (int Begin, int End) BgBrightRed { get; } = (101, 49);
        public static (int Begin, int End) BgBrightGreen { get; } = (102, 49);
        public static (int Begin, int End) BgBrightYellow { get; } = (103, 49);
        public static (int Begin, int End) BgBrightBlue { get; } = (104, 49);
        public static (int Begin, int End) BgBrightMagenta { get; } = (105, 49);
        public static (int Begin, int End) BgBrightCyan { get; } = (106, 49);
        public static (int Begin, int End) BgBrightWhite { get; } = (107, 49);
        public static (int Begin, int End) Bold { get; } = (1, 22);
        public static (int Begin, int End) Faint { get; } = (2, 22);
        public static (int Begin, int End) Dim { get; } = (2, 22);
        public static (int Begin, int End) Italic { get; } = (3, 23);
        public static (int Begin, int End) Underline { get; } = (4, 24);
        public static (int Begin, int End) Inverse { get; } = (7, 27);
        public static (int Begin, int End) Overline { get; } = (53, 55);
    }

    public partial struct AnsiStyleBuilder
    {
        public AnsiStyleBuilder Black => Foreground(KokubanColor.Black);
        public AnsiStyleBuilder Red => Foreground(KokubanColor.Red);
        public AnsiStyleBuilder Green => Foreground(KokubanColor.Green);
        public AnsiStyleBuilder Yellow => Foreground(KokubanColor.Yellow);
        public AnsiStyleBuilder Blue => Foreground(KokubanColor.Blue);
        public AnsiStyleBuilder Magenta => Foreground(KokubanColor.Magenta);
        public AnsiStyleBuilder Cyan => Foreground(KokubanColor.Cyan);
        public AnsiStyleBuilder White => Foreground(KokubanColor.White);
        public AnsiStyleBuilder Gray => Foreground(KokubanColor.Gray);
        public AnsiStyleBuilder Grey => Foreground(KokubanColor.Grey);
        public AnsiStyleBuilder BrightBlack => Foreground(KokubanColor.BrightBlack);
        public AnsiStyleBuilder BrightRed => Foreground(KokubanColor.BrightRed);
        public AnsiStyleBuilder BrightGreen => Foreground(KokubanColor.BrightGreen);
        public AnsiStyleBuilder BrightYellow => Foreground(KokubanColor.BrightYellow);
        public AnsiStyleBuilder BrightBlue => Foreground(KokubanColor.BrightBlue);
        public AnsiStyleBuilder BrightMagenta => Foreground(KokubanColor.BrightMagenta);
        public AnsiStyleBuilder BrightCyan => Foreground(KokubanColor.BrightCyan);
        public AnsiStyleBuilder BrightWhite => Foreground(KokubanColor.BrightWhite);
        public AnsiStyleBuilder BgBlack => Background(KokubanColor.Black);
        public AnsiStyleBuilder BgRed => Background(KokubanColor.Red);
        public AnsiStyleBuilder BgGreen => Background(KokubanColor.Green);
        public AnsiStyleBuilder BgYellow => Background(KokubanColor.Yellow);
        public AnsiStyleBuilder BgBlue => Background(KokubanColor.Blue);
        public AnsiStyleBuilder BgMagenta => Background(KokubanColor.Magenta);
        public AnsiStyleBuilder BgCyan => Background(KokubanColor.Cyan);
        public AnsiStyleBuilder BgWhite => Background(KokubanColor.White);
        public AnsiStyleBuilder BgGray => Background(KokubanColor.Gray);
        public AnsiStyleBuilder BgGrey => Background(KokubanColor.Grey);
        public AnsiStyleBuilder BgBrightBlack => Background(KokubanColor.BrightBlack);
        public AnsiStyleBuilder BgBrightRed => Background(KokubanColor.BrightRed);
        public AnsiStyleBuilder BgBrightGreen => Background(KokubanColor.BrightGreen);
        public AnsiStyleBuilder BgBrightYellow => Background(KokubanColor.BrightYellow);
        public AnsiStyleBuilder BgBrightBlue => Background(KokubanColor.BrightBlue);
        public AnsiStyleBuilder BgBrightMagenta => Background(KokubanColor.BrightMagenta);
        public AnsiStyleBuilder BgBrightCyan => Background(KokubanColor.BrightCyan);
        public AnsiStyleBuilder BgBrightWhite => Background(KokubanColor.BrightWhite);
    }

}