/// <auto-generated />
using System;
using Kokuban.AnsiEscape;

namespace Kokuban
{
    public partial class Chalk
    {
        public static AnsiStyle Black => new AnsiStyle().Black;
        public static AnsiStyle Red => new AnsiStyle().Red;
        public static AnsiStyle Green => new AnsiStyle().Green;
        public static AnsiStyle Yellow => new AnsiStyle().Yellow;
        public static AnsiStyle Blue => new AnsiStyle().Blue;
        public static AnsiStyle Magenta => new AnsiStyle().Magenta;
        public static AnsiStyle Cyan => new AnsiStyle().Cyan;
        public static AnsiStyle White => new AnsiStyle().White;
        public static AnsiStyle Gray => new AnsiStyle().Gray;
        public static AnsiStyle Grey => new AnsiStyle().Grey;
        public static AnsiStyle BrightBlack => new AnsiStyle().BrightBlack;
        public static AnsiStyle BrightRed => new AnsiStyle().BrightRed;
        public static AnsiStyle BrightGreen => new AnsiStyle().BrightGreen;
        public static AnsiStyle BrightYellow => new AnsiStyle().BrightYellow;
        public static AnsiStyle BrightBlue => new AnsiStyle().BrightBlue;
        public static AnsiStyle BrightMagenta => new AnsiStyle().BrightMagenta;
        public static AnsiStyle BrightCyan => new AnsiStyle().BrightCyan;
        public static AnsiStyle BrightWhite => new AnsiStyle().BrightWhite;
        public static AnsiStyle BgBlack => new AnsiStyle().BgBlack;
        public static AnsiStyle BgRed => new AnsiStyle().BgRed;
        public static AnsiStyle BgGreen => new AnsiStyle().BgGreen;
        public static AnsiStyle BgYellow => new AnsiStyle().BgYellow;
        public static AnsiStyle BgBlue => new AnsiStyle().BgBlue;
        public static AnsiStyle BgMagenta => new AnsiStyle().BgMagenta;
        public static AnsiStyle BgCyan => new AnsiStyle().BgCyan;
        public static AnsiStyle BgWhite => new AnsiStyle().BgWhite;
        public static AnsiStyle BgGray => new AnsiStyle().BgGray;
        public static AnsiStyle BgGrey => new AnsiStyle().BgGrey;
        public static AnsiStyle BgBrightBlack => new AnsiStyle().BgBrightBlack;
        public static AnsiStyle BgBrightRed => new AnsiStyle().BgBrightRed;
        public static AnsiStyle BgBrightGreen => new AnsiStyle().BgBrightGreen;
        public static AnsiStyle BgBrightYellow => new AnsiStyle().BgBrightYellow;
        public static AnsiStyle BgBrightBlue => new AnsiStyle().BgBrightBlue;
        public static AnsiStyle BgBrightMagenta => new AnsiStyle().BgBrightMagenta;
        public static AnsiStyle BgBrightCyan => new AnsiStyle().BgBrightCyan;
        public static AnsiStyle BgBrightWhite => new AnsiStyle().BgBrightWhite;
        public static AnsiStyle Bold => new AnsiStyle().Bold;
        public static AnsiStyle Faint => new AnsiStyle().Faint;
        public static AnsiStyle Dim => new AnsiStyle().Dim;
        public static AnsiStyle Italic => new AnsiStyle().Italic;
        public static AnsiStyle Underline => new AnsiStyle().Underline;
        public static AnsiStyle Inverse => new AnsiStyle().Inverse;
        public static AnsiStyle Overline => new AnsiStyle().Overline;
    }
    
    public enum KokubanColor
    {
        Black = 30,
        Red = 31,
        Green = 32,
        Yellow = 33,
        Blue = 34,
        Magenta = 35,
        Cyan = 36,
        White = 37,
        Gray = 90,
        Grey = 90,
        BrightBlack = 90,
        BrightRed = 91,
        BrightGreen = 92,
        BrightYellow = 93,
        BrightBlue = 94,
        BrightMagenta = 95,
        BrightCyan = 96,
        BrightWhite = 97,
    }
}

namespace Kokuban.AnsiEscape
{
    public static partial class AnsiEscapeCode
    {
        public static (int Begin, int End) Black { get; } = (30, 39);
        public static (int Begin, int End) Red { get; } = (31, 39);
        public static (int Begin, int End) Green { get; } = (32, 39);
        public static (int Begin, int End) Yellow { get; } = (33, 39);
        public static (int Begin, int End) Blue { get; } = (34, 39);
        public static (int Begin, int End) Magenta { get; } = (35, 39);
        public static (int Begin, int End) Cyan { get; } = (36, 39);
        public static (int Begin, int End) White { get; } = (37, 39);
        public static (int Begin, int End) Gray { get; } = (90, 39);
        public static (int Begin, int End) Grey { get; } = (90, 39);
        public static (int Begin, int End) BrightBlack { get; } = (90, 39);
        public static (int Begin, int End) BrightRed { get; } = (91, 39);
        public static (int Begin, int End) BrightGreen { get; } = (92, 39);
        public static (int Begin, int End) BrightYellow { get; } = (93, 39);
        public static (int Begin, int End) BrightBlue { get; } = (94, 39);
        public static (int Begin, int End) BrightMagenta { get; } = (95, 39);
        public static (int Begin, int End) BrightCyan { get; } = (96, 39);
        public static (int Begin, int End) BrightWhite { get; } = (97, 39);
        public static (int Begin, int End) BgBlack { get; } = (40, 49);
        public static (int Begin, int End) BgRed { get; } = (41, 49);
        public static (int Begin, int End) BgGreen { get; } = (42, 49);
        public static (int Begin, int End) BgYellow { get; } = (43, 49);
        public static (int Begin, int End) BgBlue { get; } = (44, 49);
        public static (int Begin, int End) BgMagenta { get; } = (45, 49);
        public static (int Begin, int End) BgCyan { get; } = (46, 49);
        public static (int Begin, int End) BgWhite { get; } = (47, 49);
        public static (int Begin, int End) BgGray { get; } = (100, 49);
        public static (int Begin, int End) BgGrey { get; } = (100, 49);
        public static (int Begin, int End) BgBrightBlack { get; } = (100, 49);
        public static (int Begin, int End) BgBrightRed { get; } = (101, 49);
        public static (int Begin, int End) BgBrightGreen { get; } = (102, 49);
        public static (int Begin, int End) BgBrightYellow { get; } = (103, 49);
        public static (int Begin, int End) BgBrightBlue { get; } = (104, 49);
        public static (int Begin, int End) BgBrightMagenta { get; } = (105, 49);
        public static (int Begin, int End) BgBrightCyan { get; } = (106, 49);
        public static (int Begin, int End) BgBrightWhite { get; } = (107, 49);
        public static (int Begin, int End) Bold { get; } = (1, 22);
        public static (int Begin, int End) Faint { get; } = (2, 22);
        public static (int Begin, int End) Dim { get; } = (2, 22);
        public static (int Begin, int End) Italic { get; } = (3, 23);
        public static (int Begin, int End) Underline { get; } = (4, 24);
        public static (int Begin, int End) Inverse { get; } = (7, 27);
        public static (int Begin, int End) Overline { get; } = (53, 55);
    }

    public partial struct AnsiStyle
    {
        public AnsiStyle Black => Foreground(KokubanColor.Black);
        public AnsiStyle Red => Foreground(KokubanColor.Red);
        public AnsiStyle Green => Foreground(KokubanColor.Green);
        public AnsiStyle Yellow => Foreground(KokubanColor.Yellow);
        public AnsiStyle Blue => Foreground(KokubanColor.Blue);
        public AnsiStyle Magenta => Foreground(KokubanColor.Magenta);
        public AnsiStyle Cyan => Foreground(KokubanColor.Cyan);
        public AnsiStyle White => Foreground(KokubanColor.White);
        public AnsiStyle Gray => Foreground(KokubanColor.Gray);
        public AnsiStyle Grey => Foreground(KokubanColor.Grey);
        public AnsiStyle BrightBlack => Foreground(KokubanColor.BrightBlack);
        public AnsiStyle BrightRed => Foreground(KokubanColor.BrightRed);
        public AnsiStyle BrightGreen => Foreground(KokubanColor.BrightGreen);
        public AnsiStyle BrightYellow => Foreground(KokubanColor.BrightYellow);
        public AnsiStyle BrightBlue => Foreground(KokubanColor.BrightBlue);
        public AnsiStyle BrightMagenta => Foreground(KokubanColor.BrightMagenta);
        public AnsiStyle BrightCyan => Foreground(KokubanColor.BrightCyan);
        public AnsiStyle BrightWhite => Foreground(KokubanColor.BrightWhite);
        public AnsiStyle BgBlack => Background(KokubanColor.Black);
        public AnsiStyle BgRed => Background(KokubanColor.Red);
        public AnsiStyle BgGreen => Background(KokubanColor.Green);
        public AnsiStyle BgYellow => Background(KokubanColor.Yellow);
        public AnsiStyle BgBlue => Background(KokubanColor.Blue);
        public AnsiStyle BgMagenta => Background(KokubanColor.Magenta);
        public AnsiStyle BgCyan => Background(KokubanColor.Cyan);
        public AnsiStyle BgWhite => Background(KokubanColor.White);
        public AnsiStyle BgGray => Background(KokubanColor.Gray);
        public AnsiStyle BgGrey => Background(KokubanColor.Grey);
        public AnsiStyle BgBrightBlack => Background(KokubanColor.BrightBlack);
        public AnsiStyle BgBrightRed => Background(KokubanColor.BrightRed);
        public AnsiStyle BgBrightGreen => Background(KokubanColor.BrightGreen);
        public AnsiStyle BgBrightYellow => Background(KokubanColor.BrightYellow);
        public AnsiStyle BgBrightBlue => Background(KokubanColor.BrightBlue);
        public AnsiStyle BgBrightMagenta => Background(KokubanColor.BrightMagenta);
        public AnsiStyle BgBrightCyan => Background(KokubanColor.BrightCyan);
        public AnsiStyle BgBrightWhite => Background(KokubanColor.BrightWhite);
    }

}