name: Build-Development

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    # Build
    - run: dotnet restore
    - run: dotnet build -c Release

    # Run Unit tests
    - run: dotnet test -c Release --no-build --logger trx --results-directory $GITHUB_WORKSPACE/artifacts

    # Packaging
    - name: dotnet pack
      run: dotnet pack -c Release --no-build --version-suffix "$(versionSuffix)" -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output $GITHUB_WORKSPACE/artifacts ./src/Kokuban/Kokuban.csproj

    # Upload & Publish
    - uses: actions/upload-artifact@master
      with:
        name: Packages
        path: artifacts
