name: Build-Development

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      # Build
      - run: dotnet restore
      - run: dotnet build -c Release
      # Run Unit tests
      - run: dotnet test -c Release --no-build --logger trx --results-directory $GITHUB_WORKSPACE/artifacts
      # Packaging
      - name: dotnet pack
        run: dotnet pack -c Release --no-build --version-suffix "$(versionSuffix)" -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output $GITHUB_WORKSPACE/artifacts
      # Upload & Publish
      - uses: actions/upload-artifact@master
        with:
          name: Packages
          path: artifacts
