name: Build-Release

on:
  push:
    tags:
      - v*

jobs:
  Release:
    if: "contains(github.ref, 'refs/tags')"
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: "Set VersionSuffix for Preview"
      if: "contains(github.ref, 'refs/tags') && contains(github.ref, 'preview')"
      run: |
        echo "preview.`date '+%Y%m%d-%H%M%S'`+${GITHUB_SHA:0:6}" >> $VERSION_SUFFIX
    - name: "Get git tag"
      if: "contains(github.ref, 'refs/tags')"
      run: echo ${GITHUB_REF#refs/tags/} >> $GIT_TAG

    # Build
    - run: dotnet restore
    - run: dotnet build -c Release

    # Packaging
    - name: dotnet pack
      run: dotnet pack -c Release --no-build --version-suffix "$(versionSuffix)" -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output $GITHUB_WORKSPACE/artifacts ./src/Kokuban/Kokuban.csproj

    # Upload & Publish
    - uses: actions/upload-artifact@master
      with:
        name: Packages
        path: artifacts

    - name: "Push to NuGet.org"
      run: |
        dotnet nuget push "$GITHUB_WORKSPACE/artifacts/*.nupkg" --skip-duplicate -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json